### ISSUE TITLE
Depency libc.so.6 (GLIB 2.0) missing

### ISSUE THREAD

**Issue by Termitebug** [javitonino/jolla-settings-networking-plugin-vpn-wireguard#3]
On XA2 I can't resolve a dependency install problem. Have refreshed repositories.

**Comment by javitonino** [comment]
Uhm, that's weird. That should be provided by glibc which should be installed in all SFOS version I tested (only with the emulator though).

What Sailfish OS version are you running?
What's the output of `rpm -qi glibc --provides`? (it should include `libc.so.6(GLIBC_2.0)`)

**Comment by Termitebug** [comment]
I have 4.4.0.72 (Vanha Rauma) SFOS version. Maybe I have openrepos/lpr packages installed?
And glibc shows following:

rpm -qi glibc --provides
Name        : glibc
Version     : 2.30+git11
Release     : 1.10.2.jolla
Architecture: armv7hl
Group       : Unspecified
Size        : 9689276
License     : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
Signature   : RSA/SHA256, fri 23. september 2022 23.32.04, Key ID 5b1e398947394f23
Source RPM  : glibc-2.30+git11-1.10.2.jolla.src.rpm
Build Date  : fri 23. september 2022 23.19.44
Build Host  : phost26
Vendor      : meego

https://pastebin.com/cFBRbAmM

**Comment by javitonino** [comment]
Thanks for your data.

That's weird. In other architectures glibc provides all glibc versions starting in 2.0. However, in your armv7 system, it only lists starting from 2.4 which does not make a lot of sense.

Anyway, I published a new wireguard-go package that explicitly bumps the required version from 2.0 to 2.4 (both are older than 10 years anyway, so it shouldn't matter). Hopefully that satisfies the dependency and lets you install.

Let me know how it goes.

**Comment by Termitebug** [comment]
Yes, also imo it were a wierd thing. The dependency fix solved my problem. I installed the package without errors. Many thanks 👍. This issue can now be closed.
